Update zram-installer

diff --git a/installers/zram-installer b/installers/zram-installer
--- a/installers/zram-installer
+++ b/installers/zram-installer
@@ -19,12 +19,25 @@
 # this program. If not, see http://www.gnu.org/licenses/.
 #
 ################################################################################
+#
+# Root check
+#
+if [ `id -u` -ne 0 ] ; then
+    echo "ERROR: This script needs to be run as root or using sudo."
+    exit 99
+fi
+
+################################################################################
 # Create scripts
 #
 cat << EOF > /usr/bin/zram-start
 #!/bin/sh
 #
 # Setup zRAM swap
+# 
+# Copyright (C) 2022 Alan Doyle
+#
+# https://github.com/alandoyle/helper-scripts/
 #
 ################################################################################
 NUM_DEVICES=1
@@ -91,9 +104,12 @@ cat << EOF > /usr/bin/zram-stop
 #!/bin/sh
 #
 # Free up zRAM swap
+# 
+# Copyright (C) 2022 Alan Doyle
+#
+# https://github.com/alandoyle/helper-scripts/
 #
 ################################################################################
-
 if DEVICES=\$(grep zram /proc/swaps | awk '{print \$1}'); then
   for i in \$DEVICES; do
     echo "Stopping \$i"
